Repository sgoudham-university/SomervilleSwag, pull requests merged in 2021-03, with the labels that each got.

#33 dev/database: Start DBSource.java & DBMapper.java for Storage and Retrieval of Customer Details
  src/main/java/org/somerville/swag/data/domain/Events.java
  src/main/java/org/somerville/swag/data/entity/Customer.java
  src/main/java/org/somerville/swag/data/entity/Product.java
  src/main/java/org/somerville/swag/data/entity/state/Guest.java
  src/main/java/org/somerville/swag/data/entity/state/LoggedIn.java
  src/main/java/org/somerville/swag/data/service/LoggingService.java
  src/main/java/org/somerville/swag/data/service/LoggingServiceImpl.java
  src/main/java/org/somerville/swag/data/service/util/ClockImpl.java
  src/main/java/org/somerville/swag/data/service/util/ClockStub.java
  src/main/java/org/somerville/swag/data/source/DBExecute.java
  src/main/java/org/somerville/swag/data/source/DBMapper.java
  src/main/java/org/somerville/swag/data/source/DBSource.java
  src/main/java/org/somerville/swag/data/source/SQLiteConnection.java
  src/main/java/org/somerville/swag/data/source/SQLiteExecute.java
  src/main/java/org/somerville/swag/data/source/SQLiteSource.java
  src/main/java/org/somerville/swag/data/source/util/Constants.java
  src/main/resources/database/PopulateProductTable.sql
  src/test/java/org/somerville/swag/data/service/LoggingServiceImplTest.java
  src/test/java/org/somerville/swag/data/service/util/ClockImplTest.java
  src/test/java/org/somerville/swag/data/source/DBMapperTest.java
  src/test/java/org/somerville/swag/data/source/DBPopulateTest.java
  src/test/java/org/somerville/swag/data/source/MyTextFileWriterTest.java
  src/test/java/org/somerville/swag/data/source/SQLiteExecuteTest.java
  src/test/java/org/somerville/swag/data/source/SQLiteSourceTest.java
  src/test/resources/database/TestSecondSomervilleSwagDB.db
Labels: A, B, C

#22 dev/productdisplay - Add entities to UI
  src/main/java/org/somerville/swag/data/entity/Customer.java
  src/main/java/org/somerville/swag/data/entity/Order.java
  src/main/java/org/somerville/swag/data/entity/OrderLine.java
  src/main/java/org/somerville/swag/display/Basket.form
  src/main/java/org/somerville/swag/display/Basket.java
  src/main/java/org/somerville/swag/display/JFrameBuilder.java
  src/main/java/org/somerville/swag/display/LandingPage.form
  src/main/java/org/somerville/swag/display/LandingPage.java
  src/main/java/org/somerville/swag/display/LogIn.form
  src/main/java/org/somerville/swag/display/LogIn.java
  src/main/java/org/somerville/swag/display/Purchase.form
  src/main/java/org/somerville/swag/display/Purchase.java
  src/main/java/org/somerville/swag/display/SignUp.form
  src/main/java/org/somerville/swag/display/SignUp.java
  src/test/java/org/somerville/swag/display/LandingPageTest.java
Labels: D

#38 dev/customer: Implement Customer Business Logic
  pom.xml
  src/main/java/org/somerville/swag/data/domain/Events.java
  src/main/java/org/somerville/swag/data/entity/Customer.java
  src/main/java/org/somerville/swag/data/entity/CustomerState.java
  src/main/java/org/somerville/swag/data/entity/Order.java
  src/main/java/org/somerville/swag/data/entity/OrderLine.java
  src/main/java/org/somerville/swag/data/entity/state/Guest.java
  src/main/java/org/somerville/swag/data/entity/state/LoggedIn.java
  src/main/java/org/somerville/swag/data/service/LoggingService.java
  src/main/java/org/somerville/swag/data/service/LoggingServiceImpl.java
  src/main/java/org/somerville/swag/data/source/DBExecute.java
  src/main/java/org/somerville/swag/data/source/DBMapper.java
  src/main/java/org/somerville/swag/data/source/DBSource.java
  src/main/java/org/somerville/swag/data/source/SQLiteExecute.java
  src/main/java/org/somerville/swag/data/source/SQLiteSource.java
  src/main/java/org/somerville/swag/data/source/util/Constants.java
  src/main/java/org/somerville/swag/display/Basket.form
  src/main/java/org/somerville/swag/display/Basket.java
  src/main/java/org/somerville/swag/display/JFrameBuilder.java
  src/main/java/org/somerville/swag/display/LandingPage.form
  src/main/java/org/somerville/swag/display/LandingPage.java
  src/main/java/org/somerville/swag/display/LogIn.form
  src/main/java/org/somerville/swag/display/LogIn.java
  src/main/java/org/somerville/swag/display/Purchase.form
  src/main/java/org/somerville/swag/display/Purchase.java
  src/main/java/org/somerville/swag/display/SignUp.form
  src/main/java/org/somerville/swag/display/SignUp.java
  src/main/java/org/somerville/swag/engine/App.java
  src/main/java/org/somerville/swag/engine/Main.java
  src/main/resources/database/PopulateProductTable.sql
  src/test/java/org/somerville/swag/data/entity/CustomerTest.java
  src/test/java/org/somerville/swag/data/entity/state/GuestStateTest.java
  src/test/java/org/somerville/swag/data/source/DBMapperTest.java
  src/test/java/org/somerville/swag/data/source/SQLiteExecuteTest.java
  src/test/java/org/somerville/swag/data/source/SQLiteSourceTest.java
  src/test/resources/database/TestInsertCustomerScript.sql
  src/test/resources/database/TestSecondSomervilleSwagDB.db
Labels: A, B, C, D
